### ISSUE TITLE
Files generated by IntrAnat: CSV/TSV, PTS...

### ISSUE THREAD

**Issue by ftadel** [ftadel/IntrAnat#11]
Unless anybody complains, I will stop generating all the files below:
![image](https://user-images.githubusercontent.com/6920058/104937677-59296a00-59ae-11eb-8f1c-911fa7eb6102.png)

Old file (CSV ftract):  **Gre_2021_TESt.csv** 
New file (BIDS):  **sub-gre2021test_electrodes.tsv**    

@maciej-jedynak @olivierdavidinserm
Do you really need to have ALL the columns below in the exported csv/tsv? 
If you don't please tell me which ones I can discard.
And please address the side questions in the list.

```
    GreyWhite
    MarsAtlas
    MarsAtlasFull              =>     eg. [[u'R_ITCm', 79.56989247311827]]
    MarsAtlas-MNI
    MarsAtlasFull-MNI
    Freesurfer
    Freesurfer-MNI
    DKT
    DKT-MNI
    HCP-MMP1               =>   Until now this was only MNI-based, we need to compute the correct version
    HCP-MMP1-MNI
    Lausanne2008-33
    Lausanne2008-60
    Lausanne2008-125
    Lausanne2008-250
    Lausanne2008-500
    Lausanne2008-33-MNI
    Lausanne2008-60-MNI
    Lausanne2008-125-MNI
    Lausanne2008-250-MNI
    Lausanne2008-500-MNI
    AAL
    AALDilate
    AAL2018
    AAL2
    AAL3
    Broadmann    =>   Am I allowed to rename it Brodmann?
    BroadmannDilate
    Hammers
    AICHA
    Resection rate    =>   It seems like the resection are not computed anywhere, is it something to keep?
    JulichBrain      =>      v2.5 from EBRAINS
```

**Comment by maciej-jedynak** [comment]
I can't say anything about atlases we need (I personally use Lausanne-33, AAL and will use HCP). 
As for renaming, in the F-Tract code there were these Brodmann / Broadmann issues in a couple of places already anyway. 
If you rename, then it also has to be taken into account in the script that reads CSV (which will have to be adapted to TSV and your other changes anyway).

**Comment by ftadel** [comment]
All the files actually used by some software, relying on its conventions of format or naming (ImaGIN, the Lyon software, the ftract atlas generation scripts, and IntrAnat itself).

To avoid any disruption and any re-coding of third-party tools, I will just generate the new .tsv files ON TOP of all the other existing files...
